# Generated by Django 5.1.3 on 2024-12-10 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_genre_name_alter_profile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="Can't be under 18", null=True, validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
