# Generated by Django 5.1.3 on 2024-12-04 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_musician'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='concertgoers',
            field=models.ManyToManyField(blank=True, related_name='concertgoers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concert',
            name='festival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to='events.festival'),
        ),
        migrations.AddField(
            model_name='concert',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='concerts', to='accounts.genre'),
        ),
    ]
