# Generated by Django 5.1.3 on 2024-12-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_musician'),
        ('events', '0002_concert_concertgoers_concert_festival_concert_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='festival_genres', to='accounts.genre'),
        ),
    ]
