# Generated by Django 5.1.3 on 2024-12-09 20:00

import NoteAlongProject.events.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_genre_name_alter_profile_age_and_more'),
        ('events', '0003_festival_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(validators=[NoteAlongProject.events.validators.DateValidator()]),
        ),
        migrations.AlterField(
            model_name='concert',
            name='genres',
            field=models.ManyToManyField(related_name='concerts', to='accounts.genre'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='concert',
            name='title',
            field=models.CharField(error_messages={'unique': 'Seems like the genre is already registered'}, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='festival',
            name='end_date',
            field=models.DateTimeField(validators=[NoteAlongProject.events.validators.DateValidator()]),
        ),
        migrations.AlterField(
            model_name='festival',
            name='genres',
            field=models.ManyToManyField(related_name='festival_genres', to='accounts.genre'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='festival',
            name='start_date',
            field=models.DateTimeField(validators=[NoteAlongProject.events.validators.DateValidator()]),
        ),
    ]
